Hwc scheduler wasa
PSMRI/HWC-Scheduler-UI pull request #61
Opened 2024-11-30 07:35 UTC by NKOKKILIGADDA87

## 📋 Description

JIRA ID: 

Please provide a summary of the change and the motivation behind it. Include relevant context and details.

---

## ✅ Type of Change

- [ ] 🐞 **Bug fix** (non-breaking change which resolves an issue)
- [ ] ✨ **New feature** (non-breaking change which adds functionality)
- [ ] 🔥 **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🛠 **Refactor** (change that is neither a fix nor a new feature)
- [ ] ⚙️ **Config change** (configuration file or build script updates)
- [ ] 📚 **Documentation** (updates to docs or readme)
- [ ] 🧪 **Tests** (adding new or updating existing tests)
- [ ] 🎨 **UI/UX** (changes that affect the user interface)
- [ ] 🚀 **Performance** (improves performance)
- [ ] 🧹 **Chore** (miscellaneous changes that don't modify src or test files)

---

## ℹ️ Additional Information

Please describe how the changes were tested, and include any relevant screenshots, logs, or other information that provides additional context.

2024-11-30 08:02 UTC, sandipkarmakar3 commented
@coderabbitai review

2024-11-30 08:05 UTC, sandipkarmakar3 commented
All changes I have reviewed.
Everything is as per the requirement.
We used sessionstorage.service to store the data to session storage.
We removed all localstorage code and used session storage.
We used jwt token for validate user's session.

2024-12-09 10:53 UTC, drtechie commented on src/environments/enckey.ts
Don't commit keys.

2024-12-09 10:57 UTC, drtechie commented on src/environments/enckey.ts
Remove this file, instead add a key to the environment files.
sessionStorageEncKey: <>

In the ci template, it will

2025-01-23 08:54 UTC, sandipkarmakar3 reviewed
All changes I have reviewed.
Everything is as per the requirement.
We used sessionstorage.service to store the data to session storage.
We removed all localstorage code and used session storage.
We used jwt token for validate user's session.

2025-01-31 10:02 UTC, devikasuresh20 requested changes

2025-01-31 10:02 UTC, devikasuresh20 commented on package-lock.json
> +  "name": "hwc-scheduler-ui-next",
@sandipkarmakar3 Pls remove "-next" from name

2025-01-31 10:02 UTC, devikasuresh20 commented on package-lock.json
> +      "name": "hwc-scheduler-ui-next",
@sandipkarmakar3 Pls remove "-next" from name

2025-01-31 10:02 UTC, devikasuresh20 commented on src/app/app.component.spec.ts
> +  it(`should have as title 'HWC-SCHEDULER-UI-NEXT'`, () => {
@sandipkarmakar3 Pls remove "-next" from the title

2025-01-31 10:02 UTC, devikasuresh20 commented on src/app/app.component.spec.ts
> +    expect(app.title).toEqual('HWC-SCHEDULER-UI-NEXT');
@sandipkarmakar3 Pls remove "-next" from the title

2025-01-31 10:02 UTC, devikasuresh20 commented on src/app/app.component.spec.ts
> +    expect(compiled.querySelector('.content span')?.textContent).toContain('HWC-SCHEDULER-UI-NEXT app is running!');
@sandipkarmakar3 Pls remove "-next" from the title

2025-01-31 10:02 UTC, devikasuresh20 commented on src/environments/environment.development.ts
> +const TM_API = `${tmIP}hwc-facility-service-v1.0/`;
@sandipkarmakar3 Remove "-v1.0" from hwc-facility-service

2025-01-31 10:02 UTC, devikasuresh20 commented on src/environments/environment.prod.ts
> +const TM_API = `${tmIP}hwc-facility-service-v1.0/`;
@sandipkarmakar3 Remove "-v1.0" from hwc-facility-service

2025-01-31 11:02 UTC, sandipkarmakar3 commented on src/environments/environment.prod.ts
> +const TM_API = `${tmIP}hwc-facility-service-v1.0/`;
done

2025-01-31 11:02 UTC, sandipkarmakar3 commented on src/environments/environment.development.ts
> +const TM_API = `${tmIP}hwc-facility-service-v1.0/`;
done

2025-01-31 11:02 UTC, sandipkarmakar3 commented on src/app/app.component.spec.ts
> +    expect(compiled.querySelector('.content span')?.textContent).toContain('HWC-SCHEDULER-UI-NEXT app is running!');
done

2025-01-31 11:02 UTC, sandipkarmakar3 commented on src/app/app.component.spec.ts
> +    expect(app.title).toEqual('HWC-SCHEDULER-UI-NEXT');
done

2025-01-31 11:02 UTC, sandipkarmakar3 commented on src/app/app.component.spec.ts
> +  it(`should have as title 'HWC-SCHEDULER-UI-NEXT'`, () => {
done

2025-01-31 11:03 UTC, sandipkarmakar3 commented on package-lock.json
> +      "name": "hwc-scheduler-ui-next",
done

2025-01-31 11:03 UTC, sandipkarmakar3 commented on package-lock.json
> +  "name": "hwc-scheduler-ui-next",
done

2025-01-31 11:05 UTC, merged